function dispDisplacementComparison(ds, u, deformScale)
  figure('Renderer', 'zbuffer');

  gf_plot( ds.mfu, u, ...
           'deformed_mesh', 'on',...
           'norm', 'on', ...
           'deformation', u, ...
           'deformation_mf', ds.mfu, ...
           'deformation_scale', deformScale, ...
           'disp_options', 'off' );
  title('Displacement u');
end
